version: "2.1"
orbs:
  node: circleci/node@5.0.2
  aws-s3: circleci/aws-s3@3.1
jobs:
  build:
    docker:
      - image: "cimg/node:18.15"
    steps:
      - node/install:
        node-version: "18.15"
      - checkout
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-region: AWS_REGION
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: portfolio
          to: s3://portfolio106191034073/
      - run:
          name: Install Front-End Dependencies
          command: npm run install
      - run:
          name: Front-End Build
          command: npm run build
      # deploy
      - aws-s3/copy:
          arguments: "--dryrun"
          from: portfolio/build/*
          to: s3://portfolio106191034073
workflows:
  portfolio:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
